version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redisdata:/data

  django_celery_uploader:
    build: .
    restart: always
    volumes:
      - media_value:/app/media/
    ports:
     - '8000:8000'
    depends_on:
      - redis
    env_file:
      - ./.env
  
  celery:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - django_celery_uploader
    command: celery -A django_celery_uploader.celery worker -l INFO
    
volumes:
  media_value:
